title: "[Announcement] "
body:
  - type: markdown
    attributes:
      value: |
        メンテナーからのお知らせを投稿してください。

  - type: textarea
    id: content
    attributes:
      label: 内容
      description: お知らせの内容を記述してください
    validations:
      required: true
