blank_issues_enabled: false
contact_links:
  - name: "質問 (Q&A)"
    url: https://github.com/lurest-inc/github-starter-kit/discussions/categories/q-a
    about: 使い方やトラブルに関する質問はこちらから
  - name: "アイデア・提案 (Ideas)"
    url: https://github.com/lurest-inc/github-starter-kit/discussions/categories/ideas
    about: 新しいアイデアや改善提案の共有はこちらから
  - name: "雑談 (General)"
    url: https://github.com/lurest-inc/github-starter-kit/discussions/categories/general
    about: プロジェクトに関する一般的な話題はこちらから
  - name: "成果の共有 (Show and tell)"
    url: https://github.com/lurest-inc/github-starter-kit/discussions/categories/show-and-tell
    about: 活用事例やカスタマイズの共有はこちらから
