title: GitHub Projects Ops Kit
description: GitHub Projects の初期構築から運用分析までを自動実行する運用キット
theme: jekyll-theme-cayman
google_analytics:
google-site-verification: google94e25d982f8dafc6
plugins:
  - jekyll-default-layout
  - jekyll-feed
  - jekyll-github-metadata
  - jekyll-mentions
  - jekyll-optional-front-matter
  - jekyll-relative-links
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-titles-from-headings
  - jemoji
