name: "② GitHub Project 拡張"

on:
  workflow_dispatch:
    inputs:
      project_number:
        description: "対象 Project の Number"
        required: true
        type: string

permissions:
  contents: read

jobs:
  extend-project:
    uses: ./.github/workflows/_reusable-extend-project.yml
    with:
      project_number: ${{ inputs.project_number }}
    secrets:
      PROJECT_PAT: ${{ secrets.PROJECT_PAT }}
